# Generated by Django 3.1 on 2021-02-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
