# Generated by Django 3.1 on 2021-02-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ament',
        ),
    ]
