# Generated by Django 3.1 on 2021-04-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
