# Generated by Django 3.0.8 on 2020-08-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20200821_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Others',
        ),
    ]
