# Generated by Django 3.1 on 2021-03-13 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educationalaid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalaid',
            name='content',
        ),
        migrations.AddField(
            model_name='educationalaid',
            name='img3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalaid',
            name='img4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalaid',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
